> <div style="padding:15px 10px 1px 10px; border-radius:10px;"><h3> Early Depression Detection in Students </h3></div>

> <p style="padding:10px;"> Fetching data from dataSet </p>

In [2]:
import pandas as pd

df = pd.read_csv("student_depression_dataset.csv")

df.head()
df.info

<bound method DataFrame.info of            id  Gender   Age           City Profession  Academic Pressure  \
0           2    Male  33.0  Visakhapatnam    Student                5.0
1           8  Female  24.0      Bangalore    Student                2.0
2          26    Male  31.0       Srinagar    Student                3.0
3          30  Female  28.0       Varanasi    Student                3.0
4          32  Female  25.0         Jaipur    Student                4.0
...       ...     ...   ...            ...        ...                ...
27896  140685  Female  27.0          Surat    Student                5.0
27897  140686    Male  27.0       Ludhiana    Student                2.0
27898  140689    Male  31.0      Faridabad    Student                3.0
27899  140690  Female  18.0       Ludhiana    Student                5.0
27900  140699    Male  27.0          Patna    Student                4.0

       Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0                0.0  8.97                 2.0               0.0
1                0.0  5.90                 5.0               0.0
2                0.0  7.03                 5.0               0.0
3                0.0  5.59                 2.0               0.0
4                0.0  8.13                 3.0               0.0
...              ...   ...                 ...               ...
27896            0.0  5.75                 5.0               0.0
27897            0.0  9.40                 3.0               0.0
27898            0.0  6.61                 4.0               0.0
27899            0.0  6.88                 2.0               0.0
27900            0.0  9.24                 1.0               0.0

            Sleep Duration Dietary Habits      Degree  \
0              '5-6 hours'        Healthy     B.Pharm
1              '5-6 hours'       Moderate         BSc
2      'Less than 5 hours'        Healthy          BA
3              '7-8 hours'       Moderate         BCA
4              '5-6 hours'       Moderate      M.Tech
...                    ...            ...         ...
27896          '5-6 hours'      Unhealthy  'Class 12'
27897  'Less than 5 hours'        Healthy         MSc
27898          '5-6 hours'      Unhealthy          MD
27899  'Less than 5 hours'        Healthy  'Class 12'
27900  'Less than 5 hours'        Healthy         BCA

      Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                       Yes               3.0
1                                        No               3.0
2                                        No               9.0
3                                       Yes               4.0
4                                       Yes               1.0
...                                     ...               ...
27896                                   Yes               7.0
27897                                    No               0.0
27898                                    No              12.0
27899                                   Yes              10.0
27900                                   Yes               2.0

      Financial Stress Family History of Mental Illness  Depression
0                  1.0                               No           1
1                  2.0                              Yes           0
2                  1.0                              Yes           0
3                  5.0                              Yes           1
4                  1.0                               No           0
...                ...                              ...         ...
27896              1.0                              Yes           0
27897              3.0                              Yes           0
27898              2.0                               No           0
27899              5.0                               No           1
27900              3.0                              Yes           1

[27901 rows x 18 columns]>

In [3]:
df2 = df.copy()

df2 = df2.drop(columns=['Work Pressure','Profession','Job Satisfaction'])

df2.head()

,id,Gender,Age,City,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,5.0,8.97,2.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,2.0,5.90,5.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,3.0,7.03,5.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,3.0,5.59,2.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,4.0,8.13,3.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0

> <p style="padding:10px;">IMPORTING LIBRARIES</p>

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
import PMeasures as Pm
print("done")

done

In [5]:
unique_values = {col: df[col].unique() for col in df.columns}
unique_values

{'id': array([     2,      8,     26, ..., 140689, 140690, 140699],
       shape=(27901,)),
 'Gender': <StringArray>
 ['Male', 'Female']
 Length: 2, dtype: str,
 'Age': array([33., 24., 31., 28., 25., 29., 30., 27., 19., 20., 23., 18., 21.,
        22., 34., 32., 26., 39., 35., 42., 36., 58., 49., 38., 51., 44.,
        43., 46., 59., 54., 48., 56., 37., 41.]),
 'City': <StringArray>
 [       'Visakhapatnam',            'Bangalore',             'Srinagar',
              'Varanasi',               'Jaipur',                 'Pune',
                 'Thane',              'Chennai',               'Nagpur',
                'Nashik',             'Vadodara',               'Kalyan',
                'Rajkot',            'Ahmedabad',              'Kolkata',
                'Mumbai',              'Lucknow',               'Indore',
                 'Surat',             'Ludhiana',               'Bhopal',
                'Meerut',                 'Agra',            'Ghaziabad',
             'Hyderabad',          'Vasai-Virar',               'Kanpur',
                 'Patna',            'Faridabad',                'Delhi',
                'Saanvi',               'M.Tech',               'Bhavna',
          ''Less Delhi'',                 'City',                  '3.0',
  ''Less than 5 Kalyan'',                 'Mira',               'Harsha',
                'Vaanya',               'Gaurav',                'Harsh',
               'Reyansh',               'Kibara',                'Rashi',
                    'ME',                'M.Com',               'Nalyan',
                 'Mihir',               'Nalini',              'Nandini',
             'Khaziabad']
 Length: 52, dtype: str,
 'Profession': <StringArray>
 [                 'Student',         ''Civil Engineer'',
                 'Architect',         ''UX/UI Designer'',
        ''Digital Marketer'',         ''Content Writer'',
  ''Educational Consultant'',                  'Teacher',
                   'Manager',                     'Chef',
                    'Doctor',                   'Lawyer',
              'Entrepreneur',               'Pharmacist']
 Length: 14, dtype: str,
 'Academic Pressure': array([5., 2., 3., 4., 1., 0.]),
 'Work Pressure': array([0., 5., 2.]),
 'CGPA': array([ 8.97  ,  5.9   ,  7.03  ,  5.59  ,  8.13  ,  5.7   ,  9.54  ,
         8.04  ,  9.79  ,  8.38  ,  6.1   ,  7.04  ,  8.52  ,  5.64  ,
         8.58  ,  6.51  ,  7.25  ,  7.83  ,  9.93  ,  8.74  ,  6.73  ,
         5.57  ,  8.59  ,  7.1   ,  6.08  ,  5.74  ,  9.86  ,  6.7   ,
         6.21  ,  5.87  ,  6.37  ,  9.72  ,  5.88  ,  9.56  ,  6.99  ,
         5.24  ,  9.21  ,  7.85  ,  6.95  ,  5.86  ,  7.92  ,  9.66  ,
         8.94  ,  9.71  ,  7.87  ,  5.6   ,  7.9   ,  5.46  ,  6.79  ,
         8.7   ,  7.38  ,  8.5   ,  7.09  ,  9.82  ,  8.89  ,  7.94  ,
         9.11  ,  6.75  ,  7.53  ,  9.49  ,  9.01  ,  7.64  ,  5.27  ,
         6.    ,  9.44  ,  5.75  ,  7.51  ,  9.05  ,  6.38  ,  8.95  ,
         9.88  ,  5.32  ,  6.27  ,  7.7   ,  8.1   ,  9.59  ,  8.96  ,
         5.51  ,  7.43  ,  8.79  ,  9.95  ,  5.37  ,  6.86  ,  8.32  ,
         9.74  ,  5.66  ,  7.48  ,  8.23  ,  8.81  ,  6.03  ,  5.56  ,
         5.68  ,  5.14  ,  7.61  ,  6.17  ,  8.17  ,  9.87  ,  8.75  ,
         6.16  ,  9.5   ,  7.99  ,  5.67  ,  8.92  ,  6.19  ,  5.76  ,
         6.25  ,  5.11  ,  5.58  ,  5.65  ,  9.89  ,  8.03  ,  6.61  ,
         9.41  ,  8.64  ,  7.21  ,  8.28  ,  6.04  ,  9.13  ,  8.08  ,
         9.96  ,  5.12  ,  8.35  ,  7.07  ,  9.6   ,  9.24  ,  8.54  ,
         8.78  ,  8.93  ,  8.91  ,  9.04  ,  6.83  ,  5.85  ,  7.74  ,
         6.41  ,  8.9   ,  7.75  ,  7.88  ,  5.42  ,  7.52  ,  7.68  ,
         8.4   ,  9.39  ,  6.84  ,  5.99  ,  8.62  ,  8.53  ,  7.47  ,
         6.78  ,  6.42  ,  9.92  ,  8.39  ,  5.89  ,  7.22  ,  6.81  ,
         9.02  ,  9.97  ,  9.63  ,  9.67  ,  5.41  ,  7.27  ,  6.05  ,
         6.85  ,  9.33  ,  5.81  ,  6.53  ,  5.98  ,  6.02  ,  6.74  ,
         5.26  ,  7.72  ,  7.39  ,  8.43  ,  9.34  ,  5.44  ,  5.82  ,
         5.72  ,  8.19  ,  8.44  ,  8.98  ,  9.37  ,  5.8   ,  7.28  ,
         7.6   ,  7.91  ,  9.17  ,  7.46  ,  9.43  ,  9.91  ,  9.36  ,
         5.16  ,  7.08  ,  9.26  ,  8.83  , 10.    ,  7.8   ,  9.46  ,
         6.63  ,  7.24  ,  6.47  ,  7.77  ,  5.06  ,  7.17  ,  8.24  ,
         6.88  ,  9.03  ,  5.08  ,  5.45  ,  8.46  ,  9.19  ,  6.36  ,
         8.73  ,  7.11  ,  9.12  ,  9.4   ,  8.11  ,  9.98  ,  5.55  ,
         8.61  ,  8.14  ,  6.89  ,  9.84  ,  5.48  ,  8.21  ,  7.82  ,
         8.55  ,  5.79  ,  8.77  ,  8.29  ,  6.92  ,  7.37  ,  9.7   ,
         6.26  ,  7.26  ,  7.5   ,  6.82  ,  7.15  ,  5.77  ,  5.91  ,
         5.1   ,  7.71  ,  9.06  ,  5.71  ,  5.84  ,  9.42  ,  6.23  ,
         6.29  ,  5.25  ,  9.69  ,  9.9   ,  6.39  ,  8.09  ,  5.83  ,
         5.47  ,  6.56  ,  8.71  ,  9.94  ,  6.69  ,  5.52  ,  7.3   ,
         7.02  ,  6.33  ,  8.07  ,  8.37  ,  8.    ,  7.79  ,  8.65  ,
         6.28  ,  7.35  ,  8.69  ,  7.12  ,  7.32  ,  7.13  ,  5.97  ,
         5.09  ,  6.91  ,  6.76  ,  6.52  ,  7.45  ,  8.56  ,  6.5   ,
         8.63  ,  8.27  ,  8.49  ,  6.59  ,  9.29  ,  5.3   ,  7.06  ,
         5.38  ,  6.65  ,  9.16  ,  8.01  ,  8.25  ,  8.02  ,  8.47  ,
         7.34  ,  8.88  ,  7.14  ,  8.42  ,  5.17  ,  9.1   ,  7.49  ,
         9.85  ,  7.42  ,  9.31  ,  6.35  ,  7.    ,  5.39  ,  5.61  ,
         9.78  ,  9.25  ,  5.69  ,  9.47  ,  8.16  ,  7.23  ,  6.46  ,
         0.    ,  8.26  ,  6.32  ,  6.77  ,  8.85  ,  5.03  ,  7.65  ,
         5.78  ,  6.24  ,  5.35  ,  6.06  ,  7.78  ,  6.64  ,  7.0625,
         6.98  ,  6.44  ,  6.09  ]),
 'Study Satisfaction': array([2., 5., 3., 4., 1., 0.]),
 'Job Satisfaction': array([0., 3., 4., 2., 1.]),
 'Sleep Duration': <StringArray>
 [        ''5-6 hours'', ''Less than 5 hours'',         ''7-8 hours'',
  ''More than 8 hours'',              'Others']
 Length: 5, dtype: str,
 'Dietary Habits': <StringArray>
 ['Healthy', 'Moderate', 'Unhealthy', 'Others']
 Length: 4, dtype: str,
 'Degree': <StringArray>
 [   'B.Pharm',        'BSc',         'BA',        'BCA',     'M.Tech',
         'PhD', ''Class 12'',       'B.Ed',        'LLB',         'BE',
        'M.Ed',        'MSc',        'BHM',    'M.Pharm',        'MCA',
          'MA',      'B.Com',         'MD',        'MBA',       'MBBS',
       'M.Com',     'B.Arch',        'LLM',     'B.Tech',        'BBA',
          'ME',        'MHM',     'Others']
 Length: 28, dtype: str,
 'Have you ever had suicidal thoughts ?': <StringArray>
 ['Yes', 'No']
 Length: 2, dtype: str,
 'Work/Study Hours': array([ 3.,  9.,  4.,  1.,  0., 12.,  2., 11., 10.,  6.,  8.,  5.,  7.]),
 'Financial Stress': <StringArray>
 ['1.0', '2.0', '5.0', '3.0', '4.0', '?']
 Length: 6, dtype: str,
 'Family History of Mental Illness': <StringArray>
 ['No', 'Yes']
 Length: 2, dtype: str,
 'Depression': array([1, 0])}

> <p style="padding:10px;">PreProcessing</p>

In [10]:
l1 = ['Saanvi','M.Tech','Bhavna',"'Less Delhi'",'City','3.0',"'Less than 5 Kalyan'",'Mira','Harsha','Vaanya','Gaurav','Harsh','Reyansh','Kibara','Rashi','ME','M.Com','Nalyan','Mihir','Nalini','Nandini',]

df2 = df2.drop(df2[df2['City'].isin(l1) ].index)

unique_values = {col: df2[col].unique() for col in df2.columns}
df2.head()

,id,Gender,Age,City,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,5.0,8.97,2.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,2.0,5.90,5.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,3.0,7.03,5.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,3.0,5.59,2.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,4.0,8.13,3.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0

In [7]:
for i in df2:
    if df2[i].dtype == 'object':
        df2[i] = LabelEncoder().fit_transform(df2[i])

> <p style="padding : 10px;">Performing Actual Training (Logistic Regression), Train Test Split and measuring Performance</p>

In [9]:
import math

X = df2.drop(columns=['Depression'])
y = df2['Depression']

X = pd.get_dummies(X, drop_first=True)

def train_and_preformance(ratio):
    X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=ratio,random_state=0)
    
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    
    LRmodel = LogisticRegression(max_iter = 1000)
    LRmodel.fit(X_train,y_train)
    
    y_pred = LRmodel.predict(X_test)
    
    cM = confusion_matrix(y_test,y_pred)
    TN,FP,FN,TP = cM.ravel()
    
    return {
        "model":LRmodel,
        "Accuracy":Pm.accuracy(TN,FP,FN,TP),
        "precision":Pm.precision(TN,FP,FN,TP),
        "recall":Pm.recall(TN,FP,FN,TP),
        "f1":Pm.fmeasure(TN,FP,FN,TP),
        "Specificity":Pm.specificity(TN,FP,FN,TP),
        "G Mean":Pm.gmean(TN,FP,FN,TP),
        "G Measure":Pm.gmeasure(TN,FP,FN,TP),
        "confusion matrix":cM,
    }
    
splitResult_90_10 = train_and_preformance(0.1)
splitResult_70_30 = train_and_preformance(0.3)

model = splitResult_70_30["model"]


# from sklearn.model_selection import StratifiedKFold, cross_val_score
# from sklearn.linear_model import LogisticRegression
# 
# model = LogisticRegression(max_iter=1000)
# 
# cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
# 
# scores = cross_val_score(model, X, y, cv=cv, scoring='accuracy')
# print("Fold Scores:", scores)
# print("Mean CV Score:", scores.mean())


print("Results of 90-10 split")
print("Accuracy\t\tPrecision\t\tRecall\t\t\tSpecificity\t\tf1Score\t\t\tG Mean\t\t\tG Measure")
print(f"{splitResult_90_10['Accuracy']}\t{splitResult_90_10['precision']}\t{splitResult_90_10['recall']}\t{splitResult_90_10['Specificity']}\t{splitResult_90_10['f1']}\t{splitResult_90_10['G Mean']}\t{splitResult_90_10['G Measure']}\t\n")
print(splitResult_90_10['confusion matrix'])

print("\nResults of 70-30 split")
print("Accuracy\t\tPrecision\t\tRecall\t\t\tSpecificity\t\tf1Score\t\t\tG Mean\t\t\tG Measure")
print(f"{splitResult_70_30['Accuracy']}\t{splitResult_70_30['precision']}\t{splitResult_70_30['recall']}\t{splitResult_70_30['Specificity']}\t{splitResult_70_30['f1']}\t{splitResult_70_30['G Mean']}\t{splitResult_70_30['G Measure']}\t\n")
print(splitResult_70_30['confusion matrix'])

Results of 90-10 split
Accuracy		Precision		Recall			Specificity		f1Score			G Mean			G Measure
0.8461262553802008	0.8546754020250149	0.8858024691358025	0.13003940588056995	0.86996059411943	0.3393953841966058	0.8700997537198784

[[ 924  244]
 [ 185 1435]]

Results of 70-30 split
Accuracy		Precision		Recall			Specificity		f1Score			G Mean			G Measure
0.8496950854956355	0.8621098380086922	0.8864513508023563	0.12588883324987488	0.8741111667501251	0.3340573697514907	0.874195876473234

[[2742  698]
 [ 559 4364]]